
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"

[[mods]] #mandatory
# The modid of the mod
modId="randomstonedropmod" #mandatory
# The version number of the mod
version="${mod_version}" #mandatory
# A display name for the mod
displayName="RandomStoneDropMod" #mandatory

authors="aurora4123" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''A mod make stone random drops with some common items added
refrenced texture and model resources(Updating irregularly):
Modern Waystones Textures - Minecraft Resource Pack : https://modrinth.com/resourcepack/modern-waystones-textures
Waystones Resprite - Minecraft Resource Pack: https://modrinth.com/resourcepack/waystones-resprite
Faithful 32x Daggers - Minecraft Resource Pack : https://modrinth.com/resourcepack/faithful-32x-daggers
'''
displayURL = "https://github.com/Aurora4123/randomStoneDropsMod"
issueTrackerURL="https://github.com/Aurora4123/randomStoneDropsMod/issues"
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.randomstonedropmod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="${forge_version_range}" #mandatory

    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.randomstonedropmod]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


